circleci/server-docker-images

.circleci/config.yml
=> Added Minor version

helm/postgresql/.helmignore, helm/postgresql/Chart.yaml, helm/postgresql/templates/NOTES.txt, helm/postgresql/templates/_helpers.tpl, helm/postgresql/templates/deployment.yaml, helm/postgresql/templates/hpa.yaml, helm/postgresql/templates/ingress.yaml, helm/postgresql/templates/service.yaml, helm/postgresql/templates/serviceaccount.yaml, helm/postgresql/templates/tests/test-connection.yaml, helm/postgresql/values.yaml
Initial commit for postgres helm chart:
- final image reference required to be updated once its public location is known
=> Init Postgres Helm Chart

postgresql/12/Dockerfile
[ONPREM-1846](https://circleci.atlassian.net/browse/ONPREM-1846)
[ONPREM-1846]: https://circleci.atlassian.net/browse/ONPREM-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Upgrade Postgres to 12.22

.circleci/config.yml, rabbitmq/3/Dockerfile
https://circleci.atlassian.net/browse/ONPREM-2261
=> [ONPREM-2261] Add initial server-rabbitmq image

helm/redis/.helmignore, helm/redis/Chart.yaml, helm/redis/templates/NOTES.txt, helm/redis/templates/_helpers.tpl, helm/redis/templates/configmap-scripts.yaml, helm/redis/templates/configmap.yaml, helm/redis/templates/headless-svc.yaml, helm/redis/templates/health-configmap.yaml, helm/redis/templates/metrics-prometheus.yaml, helm/redis/templates/metrics-svc.yaml, helm/redis/templates/networkpolicy.yaml, helm/redis/templates/pdb.yaml, helm/redis/templates/prometheusrule.yaml, helm/redis/templates/psp.yaml, helm/redis/templates/redis-master-statefulset.yaml, helm/redis/templates/redis-master-svc.yaml, helm/redis/templates/redis-node-statefulset.yaml, helm/redis/templates/redis-role.yaml, helm/redis/templates/redis-rolebinding.yaml, helm/redis/templates/redis-serviceaccount.yaml, helm/redis/templates/redis-slave-statefulset.yaml, helm/redis/templates/redis-slave-svc.yaml, helm/redis/templates/redis-with-sentinel-svc.yaml, helm/redis/templates/secret.yaml, helm/redis/values.schema.json, helm/redis/values.yaml
Adding a copy of the redis chart
=> Add redis chart

helm/redis/.helmignore, helm/redis/Chart.yaml, helm/redis/templates/NOTES.txt, helm/redis/templates/_helpers.tpl, helm/redis/templates/configmap-scripts.yaml, helm/redis/templates/configmap.yaml, helm/redis/templates/headless-svc.yaml, helm/redis/templates/health-configmap.yaml, helm/redis/templates/metrics-prometheus.yaml, helm/redis/templates/metrics-svc.yaml, helm/redis/templates/networkpolicy.yaml, helm/redis/templates/pdb.yaml, helm/redis/templates/prometheusrule.yaml, helm/redis/templates/psp.yaml, helm/redis/templates/redis-master-statefulset.yaml, helm/redis/templates/redis-master-svc.yaml, helm/redis/templates/redis-node-statefulset.yaml, helm/redis/templates/redis-role.yaml, helm/redis/templates/redis-rolebinding.yaml, helm/redis/templates/redis-serviceaccount.yaml, helm/redis/templates/redis-slave-statefulset.yaml, helm/redis/templates/redis-slave-svc.yaml, helm/redis/templates/redis-with-sentinel-svc.yaml, helm/redis/templates/secret.yaml, helm/redis/values.schema.json, helm/redis/values.yaml
=> Add redis chart to 4.7

redis/6.2/debian-10/Dockerfile
Removing bitnami deps in favor of installing manually
=> multi-stage build with binaries instead of bitnami installs

.circleci/config.yml
=> change to circleci/server-redis

.circleci/config.yml
=> fix circleci/server-redis

.circleci/config.yml
=> fix promote 4.8

helm/mongodb/values.yaml
🍒 https://github.com/circleci/server-docker-images/pull/80
=> updating mongo chart defaults

.circleci/config.yml, .gitignore, do
Jira: https://circleci.atlassian.net/browse/ONPREM-2513
=> [ONPREM-2513] Publish Helm charts to Packagecloud

helm/mongodb/Chart.yaml, helm/rabbitmq/Chart.yaml, helm/redis/Chart.yaml
bumping the chart versions so we can distribute new charts
=> bumping chart version

helm/mongodb/Chart.yaml, helm/mongodb/values.yaml, helm/rabbitmq/Chart.yaml, helm/rabbitmq/values.yaml, helm/redis/Chart.yaml, helm/redis/values.yaml
🍒 https://github.com/circleci/server-docker-images/pull/98
=> Onprem 2535/fix registry refs 4.7

helm/rabbitmq/Chart.yaml, helm/rabbitmq/values.yaml, helm/redis/Chart.yaml
🍒 https://github.com/circleci/server-docker-images/pull/102
=> Onprem 2535/remove hard coded imagepull secrets 4.8

helm/rabbitmq/Chart.yaml, helm/rabbitmq/values.yaml, helm/redis/Chart.yaml
🍒 https://github.com/circleci/server-docker-images/pull/102
=> Onprem 2535/remove hard coded imagepull secrets 4.7

.circleci/config.yml, do
* Enable validation on the Postgres chart
* Add version check for charts when there are changes
=> 🍒 Add version check for charts when there are changes (#108)

rabbitmq/3/Dockerfile
```
\Enabling all stable feature flags...
Enabling all feature flags ...
All stable feature flags have been enabled
```
=> Fix RabbitMQ image

README.md
https://circleci.atlassian.net/browse/ONPREM-2465
=> [ONPREM-2465] Flesh out README a bit

redis/6.2/debian-10/Dockerfile
updating redis version to 6.2.20
=> Update redis to 6.2.20

redis/6.2/debian-10/Dockerfile
🍒 https://github.com/circleci/server-docker-images/pull/126
=> updating redis to 6.2.20
